### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant "GLOB_BRACE" 

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-client#19]
> I also noticed a fatal error on the 'Scanner' page:
> 
> ```
> Fatal error: Uncaught Error: Undefined constant "GLOB_BRACE" in /var/www/html/wp-content/plugins/wp-pronamic-client/admin/virus-scanner.php:78
> 
> Stack trace:
> #0 /var/www/html/wp-content/plugins/wp-pronamic-client/classes/Plugin.php(135): include()
> #1 /var/www/html/wp-content/plugins/wp-pronamic-client/classes/Admin.php(378): Pronamic\WordPress\PronamicClient\Plugin->display('admin/virus-sca…')
> #2 /var/www/html/wp-includes/class-wp-hook.php(324): Pronamic\WordPress\PronamicClient\Admin->page_virus_scanner('')
> #3 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
> #4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
> #5 /var/www/html/wp-admin/admin.php(259): do_action('pronamic_page_p…')
> #6 {main} thrown in /var/www/html/wp-content/plugins/wp-pronamic-client/admin/virus-scanner.php on line 78
> ```
> 
> From the docs (https://www.php.net/manual/en/function.glob.php):
> 
> > Note: `GLOB_BRACE` is not available on some non GNU systems, like Solaris or Alpine Linux.

_Originally posted by @rvdsteege in https://github.com/pronamic/wp-pronamic-client/issues/18#issuecomment-2022498394_

Maybe remove the 'virus scanner', i haven't used this feature in years.

**Comment by rvdsteege** [comment]
I also never use it and am fine with removing it.
